### ISSUE TITLE
import limit is not set if peeringdb not found

### ISSUE THREAD

**Issue by budiwijaya** [pierky/arouteserver#105]
Using arouteserver version `1.14.0`

When a client is not having a peeringdb record, the import limit will not be set.

My general.yaml config:
```
...
    max_prefix:
      action: "shutdown"
      restart_after: 5
      general_limit_ipv4: 1000
      general_limit_ipv6: 100
      count_rejected_routes: false
      peering_db:
        enabled: true
...
```

Example one of the clients that did not have peeringdb record: [AS136127](https://www.peeringdb.com/asn/136127)

Config generated:

```
...
protocol bgp AS136127_1 {
        description "xxxx";

        local as xxxx;
        neighbor 103.x.x.x as 136127;
        rs client;

        passive on;
        ttl security off;

        interpret communities off;

        # ---------------------------------------
        ipv4 {
        table master4;




        import table on;

        import keep filtered on;

        import filter receive_from_AS136127_1;
        export filter announce_to_AS136127_1;

        # ---------------------------------------
        };

                }
...
```

The documentation says, it should fallback to the value of `general_limit_ipv4`.
