### ISSUE TITLE
add percentage to PDB maxprefix suggestions

### ISSUE THREAD

**Issue by job** [pierky/arouteserver#12]
I have the following configuration

```
    max_prefix:
      action: "restart"
      restart_after: 15
      peering_db: True
```

but some of the IX participants fill into peeringdb their exact route announcement count rather than a recommendation on what others should configure. I think arouteserver should add "absolute 100" and then also increase with say 15%. This will prevent flapping with the small ones
