### ISSUE TITLE
remove enforce_origin_in_as_set / enforce_prefix_in_as_set

### ISSUE THREAD

**Issue by job** [pierky/arouteserver#22]
I see IXPs deploying arouteserver with the following config

```
cfg:
  filtering:
    irrd:   
      enforce_origin_in_as_set: False
      enforce_prefix_in_as_set: False
```

I think this defeats the entire purpose of using aroutserver. Both options shouldn't be user configurable - if people want to produce non-filtering route servers they can look elsewhere. By making it user configurable, two things happen: an entire exchange goes unfiltered, which is useless - and it enables exchanges to make exceptions per participant, an extremely unhealthy proposition.

I understand flexibility is a nice thing to have, but in this case the flexibility only offers poor choices and as such I'd argue that it is simply removed.
