### ISSUE TITLE
Clarity on local network input format

### ISSUE THREAD

**Issue by MHammett** [pierky/arouteserver#25]
I had to try a few combinations of input formats to get the configure command to accept my comma-separated list of local networks.

`List of local networks
======================

A list of local IPv4/IPv6 networks must be provided here: routes announced by
route server clients for these prefixes will be filtered out.

Please enter a comma-separated list of local networks: 206.71.10.0/24, 2001:504:45:10::/64
Invalid input: a list of IP prefixes is expected. ' 2001:504:45:10::/64' is invalid.
Please enter a comma-separated list of local networks: 206.71.10.0/24, 2001:504:45:10::0/64
Invalid input: a list of IP prefixes is expected. ' 2001:504:45:10::0/64' is invalid.
Please enter a comma-separated list of local networks: 206.71.10.0/24, 2001:504:45:10::
Invalid input: a list of IP prefixes is expected. ' 2001:504:45:10::' is invalid.
Please enter a comma-separated list of local networks: 206.71.10.0/24,2001:504:45:10::/64`

Maybe something to silently discard the entered spaces or an example of the desired format.

**Comment by job** [comment]
This is the format:

```
    # YYCIX peering lan prefix
    global_black_list_pref:
      - prefix: "206.126.225.0"
        length: 24
        comment: "Local network"
      - prefix: "2001:504:2f::"
        length: 64
        comment: "Local network"
```
