### ISSUE TITLE
Try harder to find AS-SETs

### ISSUE THREAD

**Issue by job** [pierky/arouteserver#7]
With a minimal configuration like below, arouteserver should query PeeringDB for the AS-SET and use the one found there rather than only expand AS15169.

```
clients:
  - asn: 15169
    ip:
    - "206.126.225.128"
    - "2001:504:2f::1:5169:1"
```

Using `AS-GOOGLE` instead of `AS15169` should be the behaviour if `cfg.filtering.peering_db: True`
